export {default as CardSplitting} from './CardSplitting'
export {default as KnightCovering} from './KnightCovering'
export {default as OneMax} from './OneMax'
export {default as Queens} from './Queens'
export {default as SortingNumbers} from './SortingNumbers'
export {default as TextMatching} from './TextMatching'
