import {CREATURE_COUNT} from '../constants'

export const CREATURE_GRID_TILE_WIDTH = 24
export const CREATURE_GRID_TILE_HEIGHT = 24
export const CREATURE_GRID_TILES_PER_ROW = 40
export const CREATURE_GRID_TILES_PER_COLUMN = CREATURE_COUNT / CREATURE_GRID_TILES_PER_ROW

export const VIEW_PADDING_START_X = 32
export const VIEW_PADDING_START_Y = 32
export const VIEW_PADDING_END_X = 32
export const VIEW_PADDING_END_Y = 32
