import {FRAMES_FOR_CREATURE_FITNESS} from '../../constants'

export const FRAMES_FOR_FINAL_FITNESS_VIEW = 120 // 2 seconds at 60fps
export const FRAMES_BEFORE_ADVANCING_GENERATION =
  FRAMES_FOR_CREATURE_FITNESS + FRAMES_FOR_FINAL_FITNESS_VIEW
